"""
Example: Using Keycloak Authentication in FastAPI Routes

This example shows how to use the Keycloak authentication
dependencies in your route handlers.
"""

from fastapi import APIRouter, Depends, HTTPException, status
from typing import Dict, Any

from app.core.auth_dependencies import (
    get_current_user,
    require_roles,
    create_role_dependency,
)

router = APIRouter(prefix="/example", tags=["Examples"])

# Create reusable role dependencies
admin_required = create_role_dependency(["ADMIN"])
manager_required = create_role_dependency(["MANAGER", "ADMIN"])


# ============================================================================
# Example 1: Public Route (No Authentication)
# ============================================================================

@router.get("/public")
async def public_endpoint():
    """
    Public route - accessible without authentication.
    Useful for health checks, documentation, login pages.
    """
    return {"message": "This is public, no auth required"}


# ============================================================================
# Example 2: Protected Route (Any Authenticated User)
# ============================================================================

@router.get("/protected")
async def protected_endpoint(user: Dict[str, Any] = Depends(get_current_user)):
    """
    Protected route - requires valid JWT token.
    
    Returns:
        - 401 Unauthorized if token is missing or invalid
        - User information if authenticated
    """
    return {
        "message": "Hello authenticated user",
        "username": user["username"],
        "realm": user["realm"],
        "roles": user["roles"],
    }


# ============================================================================
# Example 3: Role-Based Access Control (Requires ADMIN Role)
# ============================================================================

@router.delete("/admin/users/{user_id}")
async def delete_user(
    user_id: int,
    user: Dict[str, Any] = Depends(admin_required)
):
    """
    Admin-only route - requires ADMIN role.
    
    Returns:
        - 401 Unauthorized if token is missing or invalid
        - 403 Forbidden if user lacks ADMIN role
        - Success message if authorized
    """
    return {
        "message": f"User {user_id} deleted by {user['username']}",
        "deleted_by_admin": user["username"],
    }


# ============================================================================
# Example 4: Multiple Roles (MANAGER or ADMIN)
# ============================================================================

@router.post("/reports/generate")
async def generate_report(
    report_type: str,
    user: Dict[str, Any] = Depends(manager_required)
):
    """
    Report generation - requires MANAGER or ADMIN role.
    
    Returns:
        - 401 Unauthorized if token is missing or invalid
        - 403 Forbidden if user lacks MANAGER or ADMIN role
        - Success message if authorized
    """
    return {
        "message": f"Report generated by {user['username']}",
        "report_type": report_type,
        "generated_by": user["username"],
        "user_roles": user["roles"],
    }


# ============================================================================
# Example 5: Custom Role Check
# ============================================================================

@router.put("/settings/update")
async def update_settings(
    setting_name: str,
    user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Custom role check - manually verify role in handler.
    
    This approach is useful for complex authorization logic.
    """
    required_roles = ["SETTINGS_MANAGER", "ADMIN"]
    user_roles = user["roles"]
    
    if not any(role in user_roles for role in required_roles):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=f"Required role(s): {', '.join(required_roles)}"
        )
    
    return {
        "message": f"Settings updated by {user['username']}",
        "setting": setting_name,
        "updated_by": user["username"],
    }


# ============================================================================
# Example 6: Accessing User Claims Directly
# ============================================================================

@router.get("/profile")
async def get_profile(user: Dict[str, Any] = Depends(get_current_user)):
    """
    Get user profile from Keycloak claims.
    
    Available in user["claims"]:
    - sub: Subject (unique user ID)
    - email: User email
    - email_verified: Whether email is verified
    - name: Full name
    - given_name: First name
    - family_name: Last name
    - preferred_username: Username
    - realm_access: Realm-wide roles
    - resource_access: Client-specific roles
    """
    claims = user["claims"]
    
    return {
        "username": claims.get("preferred_username"),
        "email": claims.get("email"),
        "name": claims.get("name"),
        "sub": claims.get("sub"),
        "realm": user["realm"],
        "roles": user["roles"],
    }


# ============================================================================
# Example 7: Conditional Logic Based on Roles
# ============================================================================

@router.get("/data/sensitive")
async def get_sensitive_data(user: Dict[str, Any] = Depends(get_current_user)):
    """
    Return different data based on user role.
    """
    user_roles = user["roles"]
    
    base_data = {
        "username": user["username"],
        "timestamp": "2025-12-29T12:00:00Z",
    }
    
    # Full data for ADMIN
    if "ADMIN" in user_roles:
        return {
            **base_data,
            "data": "Full sensitive data - visible to ADMIN",
            "internal_notes": "Detailed internal information",
        }
    
    # Limited data for MANAGER
    if "MANAGER" in user_roles:
        return {
            **base_data,
            "data": "Limited sensitive data - visible to MANAGER",
        }
    
    # Summary for regular users
    return {
        **base_data,
        "data": "Summary data - visible to authenticated users",
    }


# ============================================================================
# Integration Notes
# ============================================================================

"""
INTEGRATION CHECKLIST:

1. Add this router to your main FastAPI app:
   from app.api.example_auth import router
   app.include_router(router)

2. Update your Keycloak configuration in .env:
   KEYCLOAK_ENABLED=true
   KEYCLOAK_SERVER_URL=https://idm.timesmart.io
   KEYCLOAK_REALM=smmc-uat-prod

3. Install JWT validation packages:
   pip install -r requirements.txt

4. Testing public routes:
   curl http://localhost:8000/example/public

5. Testing protected routes (without token):
   curl http://localhost:8000/example/protected
   # Returns 401 Unauthorized

6. Testing protected routes (with valid token):
   curl -H "Authorization: Bearer <valid_jwt>" \
        http://localhost:8000/example/protected

7. Testing role-based access:
   curl -H "Authorization: Bearer <admin_jwt>" \
        -X DELETE http://localhost:8000/example/admin/users/123
   # Returns 204 if user has ADMIN role
   # Returns 403 if user lacks ADMIN role

ERROR RESPONSES:

400 Bad Request
- Malformed Authorization header

401 Unauthorized
- Missing Authorization header
- Invalid JWT signature
- Expired token
- Token issuer mismatch

403 Forbidden
- Valid JWT but user lacks required role

500 Internal Server Error
- Cannot reach Keycloak server
- Unexpected validation error

LOGGING:

- Authentication successes logged as INFO
- Authentication failures logged as WARNING
- System errors logged as ERROR
- All entries include username, realm, and roles

PERFORMANCE:

- JWKS cached for 1 hour
- Token claims cached until expiration
- Minimal overhead for repeated requests to same token
"""
